version: '3.6'
services:
  server:
    image: '${DOCKER_REGISTRY}/server:${IMAGE_TAG}'
    build:
      cache_from:
        - '${DOCKER_REGISTRY}/server:${IMAGE_TAG}'
      context: docker/ruby3.0
    volumes:
      - ./app:/var/www
    ports:
      - "80:4567"
    command: [sh, -c, "bundle install && bundle exec rackup --host 0.0.0.0 -p 4567"]